### ISSUE TITLE
Merge in cyberplant's work for a CLI

### ISSUE THREAD

**Issue by prologic** [vinces1979/pwgen#8]
Let's merge in [cyberplant/pwgen](https://github.com/cyberplant/pwgen) so we get a nice CLI and republish this as ``pwgen`` to PyPi :)

**Comment by cyberplant** [comment]
:+1: !

**Comment by cyberplant** [comment]
Awesome, @vinces1979! I can close my fork now :smile: 

Thanks @prologic for bumping this.

**Comment by prologic** [comment]
:+1: :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by vinces1979** [comment]
Ok guys everything is merged and I released a new version (0.7) on pypi with all the latest updates
https://pypi.python.org/pypi/pwgen

**Comment by cyberplant** [comment]
Yeah, I can see it updated on pypi. Thanks! :+1: :fireworks:

**Comment by prologic** [comment]
Yeah great job! :+1:


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
